name = "LabConnections"
uuid = "e9ebaa62-f26d-11e8-0a59-692f6511a9a1"
authors = ["Mattias Fält  <mattiasf@control.lth.se>", "Marcus Greiff", "Marcus Thelander Andrén"]
version = "0.1.0"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
