site_name:        LabConnections.jl
repo_url:         https://gitlab.control.lth.se/labdev/LabConnections.jl
site_description: Documentation for LabConnections.jl
site_author:      Marcus Greiff, Mattias Fält, Marcus Thelander

theme: cinder

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True

docs_dir: 'build'

pages:
  - Home: 'index.md'
  - Examples:
    - Running tests: 'examples/testing.md'
    - Running BB examples: 'examples/examples.md'
  - Guide:
    - Introduction: 'man/introduction.md'
    - Installation: 'man/installation.md'
  - API:
    - IO devices: 'lib/io_devices.md'
    - Fucntions: 'lib/functions.md'
